### PR TITLE
feat: ui-update

### PR DESCRIPTION
**Pull request by Qudusayo**
# UI Update

Made some improvements to the initial UI to make it fancier. 
Screenshot 2023-02-23 at 12 07 27

Considered performance. The `92%` there was reduced by a logging script most likely in my browser according to the message,
Screenshot 2023-02-23 at 13 17 52

### CODE REVIEW

**Comment by Olanetsoft** [comment]
Thank you so much @Qudusayo Thia ia Mzing.

Here is the preview https://article-idea-generator-git-fork-qudusayo-ui-update-olanetsoft.vercel.app/ it doesn't seem to work when you search; do you mind checking it out?

**Comment by Olanetsoft** [comment]
The UI looks great, but i think CSS is blocking the result preview or something. Check here https://article-idea-generator-q8qnijy15-olanetsoft.vercel.app/. @Qudusayo

**Comment by Qudusayo** [comment]
Issue #40 is addressed in the last commit.

I was thinking probably env wasn't set for that deployment. I tested locally and also [deployed my forked version here](https://article-idea-generator-ashy.vercel.app/)  and everything seemed to be good
Screen Recording 2023-02-23 at 14 22 38

**Comment by Qudusayo** [comment]
Looking into the network request, I noticed a 500 status code ( Internal server error ); therefore the issue is coming from the server which is most likely the env issue during the deployment.

**Comment by Olanetsoft** [comment]
> Looking into the network request, I noticed a 500 status code ( Internal server error ) when the request is submitted; therefore, the issue is coming from the server which is most likely the env issue during the deployment.

Oh i see. Thank you.

Merged!

**Pull request merged**
